// frontend-cv-chatbot/src/app/components/chat-box/chat-box.component.ts
import { Component, OnInit, ViewChild, ElementRef, AfterViewChecked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ChatService } from '../../services/chat.service';

interface Message {
  content: string;
  isUser: boolean;
}

@Component({
  selector: 'app-chat-box',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './chat-box.component.html',
  styleUrls: ['./chat-box.component.css']
})
export class ChatBoxComponent implements OnInit, AfterViewChecked {
  messages: Message[] = [];
  inputMessage = '';
  @ViewChild('messagesContainer') private messagesContainer!: ElementRef;

  constructor(private chatService: ChatService) {}

  ngOnInit() {
    this.messages.push({
      content: "How may I assist you with David's CV information?",
      isUser: false
    });
  }

  ngAfterViewChecked() {
    this.scrollToBottom();
  }

  private scrollToBottom(): void {
    try {
      this.messagesContainer.nativeElement.scrollTop = 
        this.messagesContainer.nativeElement.scrollHeight;
    } catch(err) {}
  }

  async sendMessage() {
    if (!this.inputMessage.trim()) return;

    // Add user message
    this.messages.push({
      content: this.inputMessage,
      isUser: true
    });

    const messageToSend = this.inputMessage;
    this.inputMessage = '';

    try {
      this.chatService.sendMessage(messageToSend).subscribe(
        response => {
          this.messages.push({
            content: response.answer,
            isUser: false
          });
        },
        error => {
          console.error('Error:', error);
          this.messages.push({
            content: "Sorry, I couldn't process your request at the moment.",
            isUser: false
          });
        }
      );
    } catch (error) {
      console.error('Error:', error);
    }
  }
} 
<div class="chat-container">
  <div #messagesContainer class="messages-container">
    @for (message of messages; track message) {
      <div class="message-wrapper" [class.user-message]="message.isUser">
        <div class="message" [class.user-message]="message.isUser">
          {{ message.content }}
        </div>
      </div>
    }
  </div>
  
  <div class="input-container">
    <input 
      type="text" 
      [(ngModel)]="inputMessage"
      (keyup.enter)="sendMessage()"
      placeholder="Type your message..."
    >
    <button (click)="sendMessage()">Send</button>
  </div>
</div>

// src/components/ChatBox.tsx
import React, { useState, useRef, useEffect } from 'react';

interface Message {
  content: string;
  isUser: boolean;
}

const ChatBox: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputMessage, setInputMessage] = useState('');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    // Add initial greeting message
    setMessages([{ content: "How may I assist you with David's CV information?", isUser: false }]);
  }, []);

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const sendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputMessage.trim()) return;

    // Add user message to chat
    const userMessage: Message = { content: inputMessage, isUser: true };
    setMessages(prev => [...prev, userMessage]);
    setInputMessage('');

    try {
      const response = await fetch('https://func-cv-chatbot.azurewebsites.net/api/cv-chatbot-backend', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message: inputMessage }),
      });

      const data = await response.json();
      const botMessage: Message = { content: data.answer, isUser: false };
      setMessages(prev => [...prev, botMessage]);
    } catch (error) {
      console.error('Error:', error);
      const errorMessage: Message = { 
        content: "Sorry, I couldn't process your request at the moment.", 
        isUser: false 
      };
      setMessages(prev => [...prev, errorMessage]);
    }
  };

  return (
    <div className="flex flex-col h-[600px] w-full max-w-2xl mx-auto bg-white rounded-lg shadow-md">
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((message, index) => (
          <div
            key={index}
            className={`flex ${message.isUser ? 'justify-end' : 'justify-start'}`}
          >
            <div
              className={`max-w-[70%] rounded-lg px-4 py-2 ${
                message.isUser
                  ? 'bg-blue-500 text-white'
                  : 'bg-gray-100 text-gray-800'
              }`}
            >
              {message.content}
            </div>
          </div>
        ))}
        <div ref={messagesEndRef} />
      </div>
      
      <form onSubmit={sendMessage} className="border-t p-4">
        <div className="flex space-x-4">
          <input
            type="text"
            value={inputMessage}
            onChange={(e) => setInputMessage(e.target.value)}
            className="flex-1 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Type your message..."
          />
          <button
            type="submit"
            className="px-6 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            Send
          </button>
        </div>
      </form>
    </div>
  );
};

export default ChatBox;
